name: Run Linter Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spotless
        run: make format-check

      - name: Run Checkstyle
        run: make lint
