name: Run Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21, 24 ]

    runs-on: ubuntu-latest
    name: Test on Java ${{ matrix.java-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with coverage
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: habedi/uview
